name: Deploy Next.js to AWS EC2

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Allow manual triggers

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          npm install -g pnpm
          pnpm install

      # Step 4: Build Next.js App
      - name: Build Next.js
        run: pnpm build

      # Step 5: Transfer Build to AWS EC2
      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.3  # Use a valid version
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: './out/*'
          target: '/var/www/html/'

      # Step 6: Restart Application on EC2
      - name: Restart Nginx
        uses: appleboy/ssh-action@v0.1.5  # Use a valid version
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl restart nginx
